### ISSUE TITLE
href binds failing to resolve server-side

### ISSUE THREAD

**Issue by michaelbull** [aurelia/ssr-engine#6]
**I'm submitting a bug report**

* **Library Version:**
0.1.0

**Please tell us about your environment:**
* **Operating System:**
Linux (fedora 26)

* **Node Version:**
8.9.4

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
webpack 3.11.0

* **Browser:**
Chrome Version 64.0.3282.167 (Official Build) (64-bit)

* **Language:**
TypeScript 2.7.2

**Current behavior:**
I am currently running the [ssr skeleton nav](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack-ssr) using the instructions provided (`npm run watch` && `npm run server`). I have explicitly disabled javascript in my browser (Chrome), and am loading the application on port 8080. The nav-bar link bindings (the `href.bind=` calls) are not being resolved server side, and thus there is no `href` attribute on the `<a>` tags in the nav bar. Re-enabling JS in the browser fixes this issue (in that the `href.bind`s get resolved to `href`s) - however this defeats the purpose of server-side rendering.

**Expected/desired behavior:**

* **What is the expected behavior?**
The `href.bind`s should be resolved server-side.

* **What is the motivation / use case for changing the behavior?**

Ability to provide routable navigation using the server-side rendering engine.

**Comment by JeroenVinke** [comment]
I've confirmed this behavior, although for me it's intermittent so it could very well be a timing issue.

**Comment by JeroenVinke** [comment]
@michaelbull could you give this a try? `npm install jeroenvinke/ssr-bootstrapper-webpack.git#bindings-build`

**Comment by JeroenVinke** [comment]
@michaelbull yeah it's a workaround for sure.

The problem is that the anchors haven't been updated when the aurelia-composed event is raised, which is not a problem in a browser environment. I believe that the problem is in the [mutationobserver](https://github.com/aurelia/pal-nodejs/blob/master/src/polyfills/mutation-observer.ts#L250) polyfill which is used by pal-nodejs. There's a timeout in that polyfill that seems to be causing the problem. I'll need to look into that, but I'm out of time right now, hence the workaround.

**Comment by EisenbergEffect** [comment]
We could hack our own polyfill in the future that just fires things immediately probably. I doubt there's any need for it to be async in the server context.
